apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-curator-config
  labels:
    k8s-app: elasticsearch-curator
data:
  action.yml: |-
    ---
    actions:
      1:
        action: delete_indices
        description: >-
          Delete indices older than 7 days (based on time period). Ignore
          the error if the filter does not result in an actionable
          list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
          continue_if_exception: False
          disable_action: False
        filters:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 7
  config.yml: |-
    ---
    client:
      hosts:
       - http://elasticsearch-logging
      port: 9200
    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: []